### ISSUE TITLE
normalize.css

### ISSUE THREAD

**Issue by ghost** [dhg/Skeleton#110]
Consider using [normalize.css](https://github.com/necolas/normalize.css/blob/master/normalize.css) instead of the resets? _They can of course be [minified](https://gist.github.com/3994915) and not fill the whole document._

**Comment by rizqyhi** [comment]
I have the same thought here, and hope it will realized soon.

**Comment by ghost** [comment]
I'm glad someone agrees.

**Comment by smcguinness** [comment]
A lot of the differences between normalize and resets is zeroing padding and margins. Normalize forces margin/padding to be done at the element level rather than globally forcing it. I'm actually beginning a project right now with the removed reset and utilizing normalize.css

**Comment by FlashJunior** [comment]
+1

**Comment by FlashJunior** [comment]
i made an example with:
- Skeleton 1.2 (without base.css)
- normalize.css v2.1.0
- Modernizr 2.6.2
- Respond.js v1.1.0
- some detections via Media Queries, Modernizr and Conditional Comment (for IE)

http://www.onebyte.ch/test/responsive/frameworks/skeleton/2/

**Comment by dhg** [comment]
Done :) Normalize included in v2.0 .Thanks for the push to use it!
