### ISSUE TITLE
There should be a .no-button class

### ISSUE THREAD

**Issue by meowsus** [dhg/Skeleton#112]
Hey,

I was thinking, there should be a reset class for buttons, in case the developer doesn't want a specific button to be styled, or wants the ability to reset the button to it's original format for whatever reason.

Curt

**Comment by sdrib** [comment]
Doesn't that open the door for a whole array of "no-x", "no-y" classes?

**Comment by Jackbennett** [comment]
I'd say it's best to only add things with css; You'd be better served changing the classes to .button-styled or .button-control or something implying how that style is intended.

**Comment by sdrib** [comment]
@Jackbennett exactly, this type of usage is user specific, it should not be part of this framework

**Comment by dhg** [comment]
In this specific case, I believe the right thing to do here would be create a separate style as @Jackbennett suggests. Doing something like this would pull at the thread of creating classes for all elements that "undoes" Skeleton styles.
