### ISSUE TITLE
Tabs and Toggle Panels

### ISSUE THREAD

**Issue by card1concepts** [dhg/Skeleton#118]
Hello, I did not really know where else to ask this question but I am working on my first responsive design project using skeleton, which has been awesome so far by the way!

My question is this, I noticed there is a Wordpress theme of skeleton that provides shortcodes like tabs and toggle panels. Is there a way to incorporate these in a custom non-wordpress site?

I tried pulling the styles and javascript from the wordpress theme to get them to work on a page but am missing something i think to get it all working.

Thank you for your time.

**Comment by dhg** [comment]
I'm closing this since it's over 2 years old now, but I apologize @card1concepts for never hitting you back on this one. The Skeleton Wordpress theme was a community created fork of Skeleton that I never had a chance to fully dig in to, but I really hope you resolved your issue!
