### ISSUE TITLE
Skeleton wider

### ISSUE THREAD

**Issue by polikin** [dhg/Skeleton#120]
Hi!

I took your grid and I created the same grid for wider screen (1200px). If the screen is less than 1200px, it takes the originial style. (960px). So, if you fixed some bugs, you can edit this file or let me know and I'll fix it.

Regards,

https://github.com/theresponsiveness/GetSkeleton1200

**Comment by dhg** [comment]
Hey @polikin - thanks man. I know this was from EXACTLY two years ago. Skeleton was in disrepair for quite some time, but I'm getting back into the swing of it now and just wanted to let you know it's now extremely flexible. While it still maxes by default at 960, one line of CSS can change that to adapt to a 1200px wide grid. Thanks again for reaching out and putting this here for V1.0 though.

**Comment by polikin** [comment]
you're welcome! Did you made an .scss version?
