### ISSUE TITLE
HTML Element <label> Written Incorrectly in Documentation

### ISSUE THREAD

**Issue by Scribblets** [dhg/Skeleton#122]
In the HTML markup, the way you document form fields, there is a label used that seems to describe the overall fieldset. This does not validate.

**Comment by ghost** [comment]
Do you mean [this](https://github.com/dhgamache/Skeleton/blob/master/index.html) HTML markup? If not, then give us a link to what you mean, and preferably include the message saying it doesn't validate. What are you using? W3C Validator?

**Comment by Scribblets** [comment]
![Screen Shot 2013-01-26 at 11 05 37 PM](https://f.cloud.github.com/assets/2066489/100605/e5d4e500-6836-11e2-8e24-701dc989942c.png)

Labels require the "for" attribute. When it doesn't have one, it doesn't validate with the W3C Validator. I thought this was a better solution. :)

**Comment by dhg** [comment]
I _believe_ this is solved in the docs for V2.0 of Skeleton. Closing for now, but if there's suggestions on improving form usability that makes sense, let me know!
