### ISSUE TITLE
Is there a more active fork of Skeleton?

### ISSUE THREAD

**Issue by sdrib** [dhg/Skeleton#126]
There are a load of Pull Requests that look promising but have been sitting there form months. There almost 500 forks, anyone any ideas of which one is most up to date?

**Comment by zQueal** [comment]
I'd also be **very interested** to know.

**Comment by chadwithuhc** [comment]
Yah, this is ridiculous. Who wants to man up and create the new project repo? You'll get a lot of exposure...

**Comment by sdrib** [comment]
:+1:

**Comment by jswebschmiede** [comment]
:+1:

**Comment by dmur** [comment]
I have merged several pull requests into a fork at [dmur/Skeleton](http://github.com/dmur/Skeleton) and plan to keep active

**Comment by sdrib** [comment]
@dmur looks good, will give this a spin

**Comment by zQueal** [comment]
@dmur gracias brochacho!

**Comment by digitalclutch** [comment]
very awesome.

**Comment by nickpack** [comment]
I am also maintaining an sass/scss version: https://github.com/nickpack/Skeleton-SCSS

**Comment by dhg** [comment]
Hey ya'll - this is 100% my fault. I left Skeleton in awful disrepair, but am digging through all the issues and pull requests in light of getting through a v2.0. I wrote a silly letter about it here: https://medium.com/@dhg/dear-skeleton-452f4bb07d69

@dmur Glad you forked and continued the mission elsewhere too – that's what Skeleton is all about. Being a stepping stone for building new awesome stuff. 

Sorry again to everyone for dropping the ball on this. I'm going to work hard and stay on top of the project this time around. If anyone wants to reach out to me about it – hi@getskeleton.com
