### ISSUE TITLE
useful classes phrases

### ISSUE THREAD

**Issue by klml** [dhg/Skeleton#131]
Would it be useful to have some generic phrased classes, like _class="right"_, which floates right any element and puts some margins on images?
I know its not for templating use, so not an "real" skeleton issue, but useful in the content. But I don't want to include an extra collection for these few lines of css.

some examples https://github.com/klml/usefulclassroomphrases/blob/master/ucp.css#L35

**Comment by dhg** [comment]
Hey @klml - This now exists with the utility classes in v2.0 - http://getskeleton.com/#utilities

Thanks so much for the push to create these. It's something that was fairly commonly requested.
