### ISSUE TITLE
Funky Nexus 7 Chrome view.

### ISSUE THREAD

**Issue by accurateweb-zz** [dhg/Skeleton#136]
I'm not sure if this is the place to post an issue like this but I haven't found any support forum for Skeleton, so my apologies if this is a breach of etiquette.

I have a huge display issue when viewing the site on which I'm working on my Nexus 7 via Chrome in landscape mode and Chrome (desktop) from about 977px to 1007px. There doesn't seem to be an issue with Internet Explorer 10.

As you can see in the pic, the header doesn't quite make it to the right side of the viewport; it is supposed to span the whole view port. Conversely, the content block under the navigation extends just a little too far.

Has anyone any insight about this?

Thanks

http://oaklawnwebdesigner.com/palosareachamber/preview
![screenshot_2013-07-05-13-48-09](https://f.cloud.github.com/assets/1430149/755176/d2079c30-e5a3-11e2-97d1-25e729727802.png)

**Comment by Hampy** [comment]
This could just be an instance, of not being specific enough. I was having a resize issue as well, and solved it by writing my css for the specific size, I was having a problem with. In your case ( 977px to 1007px) and then letting the media query's do the rest, it seemed to work. 

Another thing I noticed while trying to replicate this was—left chrome, right safari (mac). Which leads me to the specificity conclusion. I hope that helps.

best,

![screen shot 2013-07-05 at 10 08 27 pm](https://f.cloud.github.com/assets/255975/756092/22032cce-e5e3-11e2-9b1a-62a8c5d8f2b3.png)

**Comment by accurateweb-zz** [comment]
I must be doing something wrong because I tried targeting that specific pixel range with a media query; it did nothing. I even appended each line of CSS with !important just to see...nothing. I'm sure it's me but I just can't figure out what I'm doing. Ugh!

**Comment by dhg** [comment]
@accurateweb - I know this was a good, long while ago, but I hope whatever the issue was is resolved. That said, you bring to light something very obvious I haven't thought much about which is finding a good place for Skeleton users to communicate. Not sure what the best solution is, but I'm going to figure it out and try to promote it! Cheers.
