### ISSUE TITLE
replace reset.css with normalize.css

### ISSUE THREAD

**Issue by kamov** [dhg/Skeleton#139]
Can you use normalize.css instaed of reset.css since it's better?

**Comment by dhg** [comment]
haha, yes. yes I can. 

Normalize.css included in v2.0. Thanks for the push!

**Comment by kamov** [comment]
WOW, I forgot that you exist...

why you smiling?

**Comment by dhg** [comment]
@kamov I know. Fell off the face for a while, but trying to get back into the groove and make sure Skeleton gets the love it deserves.
