### ISSUE TITLE
Widescreen version with base grid 1280

### ISSUE THREAD

**Issue by makingthingswork** [dhg/Skeleton#143]
Is this something that is being considered? Has anyone looked to make the necessary modifications to accommodate a 1280 container?

**Comment by nightriver** [comment]
Here is on 1200px: https://github.com/polikin/GetSkeleton1200

**Comment by makingthingswork** [comment]
Cool, I'll take a look. Thanks

**Comment by nightriver** [comment]
It works for me, here is example: http://www.healthtechconference.com/

**Comment by makingthingswork** [comment]
This has been useful too see thanks, I might try to tweak it so its 1280 so I can keep the 300 columns but change it to a one-quarter and so on.

**Comment by nickpack** [comment]
@makingthingswork I have an SCSS version that has a configurable grid, if thats any use? https://github.com/nickpack/Ribs/

**Comment by dhg** [comment]
Hey ya'll - sorry for being so belated to address your issues. The new v2.0 of Skeleton still defaults to a 960px max-width, percentage based grid...but it's one line of CSS to change that max. Can easily be made 1280px. Hope that addresses the issue, but let me know if I'm pre-maturely closing. 

Thanks all.
