### ISSUE TITLE
Equal Margin

### ISSUE THREAD

**Issue by steve-acet** [dhg/Skeleton#144]
I am trying to create a layout which has three columns, each with the same gutter around them. I am not sure if this is possible, but at the moment when I have three "one-third" columns, the middle column appears to have a bigger margin than the outer 2. This makes the layout look uneven. I need this to be responsive. Any ideas?

**Comment by dhg** [comment]
Not sure how that happened on V1.0 of Skeleton, but I'm _prettttttty_ sure that's not true in V2.0 which just got releases. I know I'm about a year and some change too late in replying, but just documenting for future. Sorry for not hitting you back in a timely manner @steve-acet
