### ISSUE TITLE
Sidebar positioning

### ISSUE THREAD

**Issue by mevinsconsulting** [dhg/Skeleton#145]
I installed the theme out of the box and have an issue with the sidebar. By default, any widgets added are placed at the bottom of the main content block, even though there is plenty of room for the sidebar. Are there any known issues for this? An example can be seen at http://108.174.148.116/~vetport/. You'll see here that the Meta block (labeled Test) is not on the side, but below the main content.

Any thoughts?

**Comment by marktoce** [comment]
You have the sidebar within the content div. The content div is only eleven columns, so the sidebar is displaying within those eleven columns. Hope that helps!

**Comment by mevinsconsulting** [comment]
Thanks @marktoce - that's what I was thinking also. I installed this from a fresh download through github, so I'm surprised this issue is in the code. Any idea which file needs the code alteration? I'm using a child theme, so I'm hoping that when I do an upgrade, this problem doesn't come back.

Thanks!

**Comment by dhg** [comment]
Hey fellas - new version of Skeleton doesn't have that awkward sidenav that was in the docs, but not in the framework...so hopefully this is no longer an issue. Apologies on not getting back on this sooner, but glad to see community members helping out!
