### ISSUE TITLE
20px Gap at Bottom of Container

### ISSUE THREAD

**Issue by dhg** [dhg/Skeleton#15]
There is a mysterious and weird gap at the base of the `.container` that persists almost no matter what. Need to resolve why that is there and crush it!

**Comment by craigrodway** [comment]
I think this is the source of the issue you describe: https://github.com/dhgamache/Skeleton/blob/master/stylesheets/skeleton.css#L205

**Comment by dhg** [comment]
Hi Craig, 

Yeah, the clearfix is what makes the bottom of the `.container` clear, but it is not "adding" the 20px (it is making sure the parent is the same height as all its children). I know it's not the direct cause because it is effectively used elsewhere (960.gs) without the same result. This is one step closer though - I'll keep fiddling with it!

Thanks for your contribution and let me know if you manage to surface anything else!

Cheers
Dave

**Comment by craigrodway** [comment]
Hi Dave

You're right, 960 does have that (I hadn't noticed before). However, it uses a space rather than a period character; and changing that in skeleton.css appears to remove the bottom margin (at least on the one design I'm working on at the moment).

**Comment by dhg** [comment]
GOOD MAN! I actually had the `.clearfix` class with the correct space character, but somehow managed to put a period into the version for clearing the `container`. Thanks for the great catch! It has been updated in the source code :)

**Comment by craigrodway** [comment]
Awesome. :)
