### ISSUE TITLE
"Code Example" links on GetSkeleton.com don't work

### ISSUE THREAD

**Issue by dskvr** [dhg/Skeleton#151]
So I cared enough to submit an issue, but probably will never use Skeleton based on this fact. All the best!

**Comment by deddu** [comment]
FYI,
The links works fine for me on Chrome, IE10 and firefox. but fails on safari. 
in safari chokes on 

```
SyntaxError: Unexpected token '<'      login:0
```

**Comment by dhg** [comment]
Sorry fellas - I left Skeleton in disrepair for far too long...but code examples are getting updated and fresh ones are included w/ v2.0 and more are coming.
