### ISSUE TITLE
Window overflow at break-points 960, 768 in desktop browsers with a solid vertical scroll bar

### ISSUE THREAD

**Issue by wilirius** [dhg/Skeleton#152]
I am pretty sure this is due to not accounting for the width of the scroll bar.

I believe any css framework that uses the (container width = minimum size for that breakpoint) style will end up with this issue.

Does anyone know of a way around this that doesn't result in extra break points?

**Comment by dhg** [comment]
@wilirius I don't believe this will be an issue anymore with v2.0, so will close for now, but please correct me if I'm wrong.
