### ISSUE TITLE
Enlarge the default font 

### ISSUE THREAD

**Issue by shufengh** [dhg/Skeleton#157]
Hi there,
I'm using Skeleton for a project and found that the default font solution is a little bit small. Does anyone know what should be done to enlarge the font a bit, like to 125%? I tried to change the font itself and then the whole page looked weird.  Is it possible to just increase every field by 1.25? 

Thank you. I'm really new in CSS.

**Comment by Kagerou** [comment]
Font size is easy to change. It's in the base.css file. Change the font size from 14px/21px to something larger.

/\* #Basic Styles
================================================== */
    body {
        background: #fff;
        font: 14px/21px "HelveticaNeue", "Helvetica Neue", Helvetica, Arial, sans-serif;

**Comment by shufengh** [comment]
@Kagerou Thank you. I know this place. What I mean is to change the whole view. If I change the font here only, other parts will not look right, because the font ratio does not change, like h1-h6 and others

**Comment by Kagerou** [comment]
You should change those individually in the typography section

**Comment by pautazzo** [comment]
That's beacause all font height/leading are set in px instead of ems,
otherwise changing body font size would be enough.
Unfortunately you'll have to change every single element individually.

2014-05-17 11:43 GMT-03:00 Kagerou notifications@github.com:

> You should change those individually in the typography section
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dhg/Skeleton/issues/157#issuecomment-43408688
> .

## 

_§_ DG Anibal Pautazzo

**Comment by dhg** [comment]
Hey all - apologies on never getting back to anyone here on this. v2 of Skeleton actually does everything based on REMs, so this _should_ be quite easy to handle now, but if you run into any issues, don't hesitate to re-open or create a new issue.
