### ISSUE TITLE
Self-Clearing Goodness Fix

### ISSUE THREAD

**Issue by brainycouchmike** [dhg/Skeleton#159]
I think this is more effective for the content of the :after pseudo on the "Self-Clearing Goodness", use a CRLF instead of a space character.
    .container:after {
        content: "\00D\00A";
        display: block;
        height: 0;
        clear: both;
        visibility: hidden;
    }

**Comment by martin-sweeny** [comment]
More effective? I don't know about that. More semantic? Probably

**Comment by brainycouchmike** [comment]
Semantically, certainly improved. as to effectiveness, try it. You'll see what I mean. Add it on before and after and it cleans your floats very nicely, especially with top and bottom margins of floated children in floated parents. But that is the point, no? I'd say effectiveness is defined by the visual Rendering, which is improved by this fix. Use it or not, I just thought I would share an improvement that helped me.

**Comment by martin-sweeny** [comment]
I'm not seeing any difference here. What browser are you using ?

**Comment by brainycouchmike** [comment]
Chrome. Firefox as well, the change actually fixed the issue across the two. I can try to replicate the effect on a jsfiddle. But I'm incredibly busy, and as such, it may take me until tomorrow.

**Comment by dhg** [comment]
Hey all- I'm really sorry I never got to this in a timely fashion originally. I left Skeleton in terrible disrepair for a couple years and without an active developer. I'm back at it though and committed to continuing development. I released v2.0 a week or so ago and am making my way through all the old issues and PRs.

The new v2.0 of Skeleton uses the micro clearfix documented here: http://nicolasgallagher.com/micro-clearfix-hack/ It works like a charm and I'm extending it to use on the `.container` and `.row` as well. 

Sorry again for not getting to this sooner, but I really appreciate the suggestion and hope the new solution works well for you!
