### ISSUE TITLE
Stupid question. But important. How to remove responsive feature

### ISSUE THREAD

**Issue by pmcfernandes** [dhg/Skeleton#160]
I have a client with skeleton framework, and him told me, previous developer created a bad phone responsive layout and him want remove that. This means website never flow, mantains all aspect of desktop. I want keep skeleton framework but need remove phone responsive feature, how to do that? I tried add px of desktop in px of phone but not work changes display css prop but not work too. Any idea?

**Comment by melriksdesign** [comment]
In skeleton.css, remove the lines starting with /_Tablet (Portrait) down to /_ #Mobile (landscape) including the closing } in the Mobile section.

In layout.css, remove /\* Tablet Portrait size to standard 960 (devices and browsers) _/ through /_Mobile Portrait's closing }

It's the @media that make all the magic happen.

**Comment by pmcfernandes** [comment]
Oh. Yes i removed from skeleton.css but I don't removed anything in layout.css, i will try and give you feedback

**Comment by pmcfernandes** [comment]
Yes solved. Removed from layout.css and work. Thanks.

**Comment by gogogoairheart** [comment]
Hi there,

I am using Skeleton V1.1 but I am missing the layout.css !?
Is this version using another css ?

Would be awesome to get some help from you guys!
