### ISSUE TITLE
.Columns is styled with "display:inlline", but debugger shows the columns div is still block. Why?

### ISSUE THREAD

**Issue by kkzhang** [dhg/Skeleton#165]
![2014-09-13 7 23 40](https://cloud.githubusercontent.com/assets/575834/4258505/e0e2c172-3ad3-11e4-87dd-3748b79fddb1.png)

Why it's inline? It seems not a correct styleing.
Meanwhile, in browser, the column is still block.
![2014-09-13 7 32 22](https://cloud.githubusercontent.com/assets/575834/4258562/11ca65e6-3ad5-11e4-9705-0c4952c596a3.png)

May be a bug here?

**Comment by dhg** [comment]
Was a silly error - the display inline should have never been there. Floats will override `display: inline`. Fixed in v2.0
