### ISSUE TITLE
Source SASS or Styl file to change the base width of the grid system

### ISSUE THREAD

**Issue by davidpelayo** [dhg/Skeleton#167]
Is it possible to play with some SASS or Stylus source base code to change the measurement of the grids? I would like to generate different wide measures for the grids.

**Comment by MrMoranXP** [comment]
Try this one https://github.com/dhg/Skeleton/pull/127

**Comment by dhg** [comment]
Hey fellas - awesome there are community projects out there also addressing this, but hopefully v2.0 also psuedo-solves your issue (though it's over a year too late). The new grid is basically a % width grid with a max-width, so it's easy to change for 960 to any other width in one line of CSS.
