### ISSUE TITLE
Adding a background image

### ISSUE THREAD

**Issue by ashwani9** [dhg/Skeleton#168]
Hello,

When i add a background image in the body tag, it doesn't show up.
Is there any other place where i should add the background image.
Please help. Thanks in advance

**Comment by dhg** [comment]
This one is tough, depends on what you were trying to do. The body should be able to take a background image...in fact almost any element should be able to take a background image. What was the issue?

Apologies on super late response here.

**Comment by dhg** [comment]
Sorry, accidentally clicked close issue...

**Comment by dhg** [comment]
Just tested on Skeleton v2.0 and nothing out of the ordinary behavior here, so going to close for now, but please let me know if you find the issue persistent.

**Comment by rafic20** [comment]
I was having the same problem when trying to set the background image within an external css file (separate from skeleton.css). I was about to post a Codepen when I noticed that putting the following code within the 'style' tags in the HTML 'head' section solved the issue. 

<pre><code>
body {
    background: url(../img/art.JPG) no-repeat center center;
    background-size: cover; 
}
</code></pre>
    

The other elements styled within an external style sheet ( p, img, etc.) are working fine. Hope this helps others :)
