### ISSUE TITLE
wrong syntax: linear-gradient in base.css

### ISSUE THREAD

**Issue by kixe** [dhg/Skeleton#169]
old-syntax until 2011: linear-gradient(top, rgba(255,255,255,.2) 0%,rgba(0,0,0,.2) 100%); /\* W3C _/
new-syntax: linear-gradient(to bottom, rgba(255,255,255,.2) 0%,rgba(0,0,0,.2) 100%); /_ W3C */

more Information:
https://developer.mozilla.org/de/docs/Web/CSS/linear-gradient#History_of_the_syntax

**Comment by dhg** [comment]
No longer used in v2.0 of Skeleton. No gradients :) Thanks for documenting this at the time though!
