### ISSUE TITLE
Comparison to Foundation and Bootstrap

### ISSUE THREAD

**Issue by anugupta** [dhg/Skeleton#181]
This isn't an issue really (although maybe useful to eventually add to the site as information).

There's some mention how Skeleton is much simpler than Bootstrap / Foundation, but it would be very useful (for someone who's not really a front end guy) to understand what sorts of tradeoffs I'd make if I used Skeleton. I really love the idea of a simple, 400 line base 'framework' that doesn't require a complex toolchain just to install, but I'm a bit unclear what I'd be missing out on compared with the bigger frameworks.

**Comment by Fequois** [comment]
Basically, what you'll lose, is all the UI components. Think of Skeleton as a hammer and Bootstrap/Foundation as a toolbox. You bring the hammer to simple jobs, or when you want to build something unique, and the toolbox for larger jobs with time constraints.

If you don't want a huge, lumbering framework to make all decisions for you you're better off with something like Skeleton. If you don't really know your way around, however, you're probably better off with a larger framework with everything readily available for use already.

**Comment by deeve007** [comment]
Google is your friend. This "framework" is simple & to the point (including any docs/info), let's keep it that way.

**Comment by anugupta** [comment]
@Fequois Thanks - that's helpful.

**Comment by dhg** [comment]
@anugupta This is a great point and one that seems to cause confusion sometimes. I'm not sure the best way to document the differences, benefits, and pitfalls of using Skeleton vs. larger frameworks, but maybe there could be an easy way to do this. 

Docs seems too heavy handed to me, but potentially I could write something that addresses the differences. Or maybe, better yet, a non-partisan 3rd party would like to and I can point inquiring minds in the direction of their post :)

I'm going to close this for now, but I'm adding this as a sort of 'personal' issue to my short list of post-launch related things to take care of. 

Hope this resolves the issue, but please let me know if this isn't quite what you were looking for in an answer.
