### ISSUE TITLE
Zooming In/Out

### ISSUE THREAD

**Issue by martinbenj** [dhg/Skeleton#19]
When you zoom into a page that is marked up with skeleton, the text gets smaller relative to its container, while the opposite happens when you zoom out (text gets larger relative to its container). On a "normal" web page when you zoom in, everything gets bigger together (proportions of text to container are maintained). Any suggestions on how to make a skeleton page zoom "normally"?

**Comment by dhg** [comment]
Hey - 

I just checked this out and while the text doesn't get "larger" when shrinking, or "smaller" when enlarging, it doesn't seem to react to the scaling at all. The line-height and other measurements scale correctly, but text size stays exactly the same. 

This needs further investigation, but will be an absolutely necessary fix in the next release.

**Comment by martinbenj** [comment]
Exactly - the text stays the same size while the container gets bigger/smaller. I'm sure we'll find the culprit. Keep up the good work!

**Comment by martinbenj** [comment]
I commented out the following line of code in base.css:

-webkit-text-size-adjust: none;

Now the text size changes fine.

Here's the only use I can find for font-size-adjust:

http://webdesignernotebook.com/css/the-little-known-font-size-adjust-css3-property/

A skeleton page still responds to different window sizes without it. It seems like font-size-adjust isn't really needed. If it is used, its value should be tailored to each person's fonts/font sizes.

**Comment by dhg** [comment]
Great find - 

I also believe I implemented that for a reason on iPhone though, so I will be doing some quick testing. It will either be included only for iPhone or not at all and will fix the issue of zooming on the browser. 

Thanks for the contribution and look forward to making the necessary changes. 

Cheers
Dave

**Comment by dhg** [comment]
Hey, 

With the help of several Git user contributions, I've come up with a solution to remove the `-webkit-text-size-adjust: none;` and still have it render awesome on mobile devices and tablets. 

Thanks for the help and contribution!

Cheers
Dave
