### ISSUE TITLE
Visibility classes for various viewport sizes

### ISSUE THREAD

**Issue by dhg** [dhg/Skeleton#199]
Am considering extending the utilities section with a series of classes akin to `.u-hide-on-mobile` that will hide elements at certain sizes. Haven't considered _exactly_ how I would organize them, but just documenting the interest here. 

How does the community feel about this one? Something people are paining for? I generally don't find classes like this to be terribly useful and they make my markup feel a little messy...but I guess that's true with all utility shorthand classes.

**Comment by deeve007** [comment]
I vote no. One of the best things about Skeleton v the bloated frameworks is its leaness, which once you start adding in too many utilities that many won't use defeats that purpose. 

I'm also of the view that elements "shown" or not at different screen sizes should be a server scripting thing, so you avoid the user having to download the element at all.

**Comment by jeancarlozapata** [comment]
What about creating a repo called `Skeletons-extras` (or something like that), and leave all extra stuff outside of the main Skeleton repository, so that people can choose to add/leave out things if they like?

**Comment by deeve007** [comment]
http://www.smashingmagazine.com/2013/10/08/responsive-website-design-with-ress/

**Comment by luisrudge** [comment]
I like the idea! But I like @jeancarlozapata's idea too!

**Comment by nafoster** [comment]
I agree with @jeancarlozapata's idea. I think people enjoy Skeleton since it's bare-bones and doesn't have all the extra bloat that Foundation and Bootstrap come with. An "extras" area would totally be suitable for this idea as long as it's an optional download.

**Comment by dhg** [comment]
Alright, for now I'm going to leave out, but I'm slowly collecting ideas for "extras". Many of them will be actual links to other repos like Sass/Less versions of Skeleton, but maybe I could have a repo for additional utilities and the like. Thanks for the feedback all – going to close this for now and not add to core. 

Cheers everyone!
