### ISSUE TITLE
CSS hierarchy for .columns

### ISSUE THREAD

**Issue by deeve007** [dhg/Skeleton#202]
Rather then being targeted as such: .container .column

Can it be changed to: .row.column

Every "column" must be within a "row", but perhaps there would be occasions when a "container" wrapper is not wanted or needed?

**Comment by dhg** [comment]
@deeve007 The selectors for the grid in v2.0.2 which I just pushed out are drastically less specific and more general. It was a foolish thing to have so much specificity on them. Check it out and let me know if it satisfies the issue. 

I'm going to close for now, but feel free to re-open and discuss if you think I missed the target on this one.
