### ISSUE TITLE
Add all input types?

### ISSUE THREAD

**Issue by tomzaragoza** [dhg/Skeleton#205]
Was using an input with type="url" but the input wasn't styled properly. Should we add support for styling all different types of inputs?

**Comment by luisrudge** [comment]
Yesssss!

**Comment by dhg** [comment]
Well, my intention was to only style the most common inputs, but I think not having a type="url" input actually is kind of discouraging to using the proper inputs, so I say yes this makes sense. 

I'm going to go through the list of text input types and see if they all make sense or just an additional few.

Marking to be added in 2.0.2

**Comment by tomzaragoza** [comment]
Awesome, thanks! Would be great to have type="url" styled because on mobile, when a user is going to enter a url, the phone keyboard will have the options to enter www. or .com with just one key. At least, on my phone.

Let me know how I can help!

**Comment by dhg** [comment]
Just for reference - a couple old discussions from v1 with the same issue (just old code): https://github.com/dhg/Skeleton/pull/67
https://github.com/dhg/Skeleton/pull/91

This will be coming soon!

**Comment by dhg** [comment]
Just packaged up and pushed v2.0.2 and it includes support for search, url and tel input types. Considered adding support for others like date, datetime, etc...but didn't seem to make sense to me since I've never used one and the styles for them as inputs are so inconsistent across browsers/devices. 

Check out the commit with most of the code that resolves this issue(https://github.com/dhg/Skeleton/commit/c34806e863afa0f0059fa44864e625cff04b2048) or just go download v2.0.2

**Comment by clrnd** [comment]
Oh, sad news. I really wanted "number" and "time" styled ...

**Comment by dan1elhughes** [comment]
Why not just style input, regardless of type? If there's a particular type that is specifically not being styled, that could be overridden after the general input declaration.

**Comment by r3id** [comment]
I have added these to a version of the CSS. I got the list off W3School to make sure i had them all down correct.

/\* Forms
–––––––––––––––––––––––––––––––––––––––––––––––––– */
input[type="date"],
input[type="datetime"],
input[type="datetime-local"],
input[type="email"],
input[type="month"],
input[type="number"],
input[type="password"],
input[type="range"],
input[type="search"],
input[type="tel"],
input[type="text"],
input[type="time"],
input[type="url"],
input[type="week"],
textarea,
select

**Comment by knorthfield** [comment]
Would be good to add input[type="date"]
