### ISSUE TITLE
Missing http: line 79 of index.html

### ISSUE THREAD

**Issue by ghost** [dhg/Skeleton#23]
Maybe it's a mistype or on purpose but, 

Line 79 the src is missing the http: and seems to be causing the page to take forever to load since it's calling the file from the localhost and not actually ajax.googleapis.com.

**Comment by stewart** [comment]
This is deliberate, and is referred to as a protocol-relative URL. [Paul Irish explains](http://bit.ly/nn9TcV)

**Comment by ghost** [comment]
Interesting, never heard of that before. It causes both Chrome (13.0.782.55) and Firefox (5.0) to take over 2 minutes to load the page, soon as i add http: it works, and then i remove it again and forever to load again.

Oh well, guess it'll be fixed in time. Closing.
