### ISSUE TITLE
More Documentation

### ISSUE THREAD

**Issue by ziyaddin** [dhg/Skeleton#234]
Thank you for this project, it is awesome but user needs more documentation to work better with this stuff. Could you, please, improve Documentation of this project? Thank you!

**Comment by r3id** [comment]
I think the documentation provided is pretty good considering it's simplicity. Not sure what else needs to be covered.

What more would you be after? Can you provide some example to help rewrite anything?

**Comment by ziyaddin** [comment]
For example, using class types for whole HTML skeleton. For header, main content, footer. Anyway there are some elements that need to be highlighted for better usage.

**Comment by r3id** [comment]
Did the example not help? 

Personally I found it helped enough to get started, then the elements shown helped more to build up what I was after.

For me it's just the nav items that need to be done now.

I'm sure if you have questions someone here can answer :)

**Comment by ziyaddin** [comment]
Okay, let me say some issues:
For example, I need to set up header. In this case, do I need to write `<div class="container"></div>` or just `<div class="row"></div>`. Which is more appropriate?

**Comment by r3id** [comment]
For me I did < header > then added the container and the row

Same with < section >

I suppose it depends on your design

**Comment by r3id** [comment]
Sorry poor formatting I'm on my iPhone :)

**Comment by dhg** [comment]
Hey fellas - 

Totally valid that more documentation could be used primarily around the grid. Taking note of this and adding to my milestone for the next release. Should be super clear how/when to use which grid classes.

**Comment by ziyaddin** [comment]
@dhg thank you for support!

**Comment by ziyaddin** [comment]
@thatuxguy it's nice way, I will use it :wink:

**Comment by rafaell-lycan** [comment]
Nice idea. +1

**Comment by itsdarrylnorris** [comment]
Should we have a plan that targets what things needs to be documented? If we have a plan + child
issues we can contribute on the documentation. Otherwise, is going to pass around 6 months and nothing is going to happen (just like now).

**Comment by colincromar** [comment]
Documentation regarding offsets would be particularly helpful.
