### ISSUE TITLE
Image resize

### ISSUE THREAD

**Issue by ghost** [dhg/Skeleton#24]
Big image are not resized when you change the browser size or try to access through iPhone or iPad.
I think, you should add a CSS property to resize big image.

It could be something like that :
.container img { max-width:100%}

Or for each Media query :
    @media only screen and (min-width: 480px) and (max-width: 767px) {
        .container img { max-width:767px;}
}
.etc...

**Comment by dhg** [comment]
So there is a class called .scale-with.grid that can be applied to `<img>` tags. I don't apply it across the board because it breaks a good number of jQuery slider plugins and doesn't make sense for things like icons or other small imagery. 

Cheers!

**Comment by mraaroncruz** [comment]
In case anyone finds this (like I did), the class is `scale-with-grid` not `scale-with` and `grid`
