### ISSUE TITLE
SkeletonLESS

### ISSUE THREAD

**Issue by r3id** [dhg/Skeleton#242]
New LESS version of the boilerplate.
_link deleted_

**Comment by mwhittet** [comment]
Not the best place to advertise your version as this is mostly for tracking issues but needless to say, I will be taking a look. Was thinking of doing a SASS version ;-)

**Comment by benhinchley** [comment]
@mwhittet there is already a sass version [Skeleton-Sass](https://github.com/whatsnewsaes/Skeleton-Sass)

**Comment by r3id** [comment]
I agree, was not sure where else to put it.

There was a version for  LESS before I wrote this, it did not originally take advantage of what less could do. It's not better than it was :)

There are still bits I want to add and also try to reduce the code a little.

I haven't used sass so can't really comment.

**Comment by mwhittet** [comment]
@benhinchley thanks mate, will take a look.

@thatuxguy its all good and looks great btw. Always been a SASS man myself but have used LESS in the past.

**Comment by r3id** [comment]
@mwhittet i always thought they were very much the same thing,Well at least have the same idea behind them. Below is an interesting "vs." article on the two
https://css-tricks.com/sass-vs-less/

**Comment by rafaell-lycan** [comment]
Perhaps we can distribute the Framework in modules and in Less and Sass components.

+1

**Comment by r3id** [comment]
closing this thread now as i can't maintain it any longer.
