### ISSUE TITLE
Nested columns issue? 

### ISSUE THREAD

**Issue by yanasakellion** [dhg/Skeleton#254]
Hello - thank you for the beautiful work, have been using and plan on using skeleton in the future. 
Does anyone know how to nest columns under a new skeleton update? 

In the previous version .alpha and .omega classes were used to account for proper sizing of the nested columns. 

Now it seems i've lost ability for any precise nesting. Would something of this sort even be possible?

![screen shot 2015-02-20 at 11 40 35 pm](https://cloud.githubusercontent.com/assets/5974586/6312890/37a4ddf6-b95a-11e4-9e8a-b18842ca2b8c.png)

I've been able to neat .one-half, .one-third and .two-thirds classes within any other column with somewhat ok results, but doesn't seem like an ideal solution for a more precise grid, as offsetting any of these classes becomes rather arbitrary.

Thank you!

**Comment by susedan** [comment]
May I ask why you are nesting them in this fashion? While it could be accomplished with some manipulation of the column margins, creating a grid like this could quickly become unnecessarily complex.

**Comment by yanasakellion** [comment]
Normally, I would avoid such structuring. However, there are certain situations in which this nesting is necessary such as any type of a multi-content side bar.

 I understand that skeleton is geared towards working in rows, but every now and then there is a situation when sidebar is needed. Surely, a custom class can be written it just seems like an odd choice to take out the .alpha and .omega classes out of this version of framework.

**Comment by aqeelfikree** [comment]
The developer doesn't recommend it.

Mentioned in [Skeleton homepage](http://getskeleton.com):
Note: columns can be nested, but it's not recommended since Skeleton's grid has %-based gutters, meaning a nested grid results in variable with gutters (which can end up being _really_ small on certain browser/device sizes)

**Comment by yanasakellion** [comment]
Thanks, everyone.
