### ISSUE TITLE
Position:fixed;

### ISSUE THREAD

**Issue by madeinside** [dhg/Skeleton#260]
Hello,
I've got a problem with <code>position:fixed</code> inside the grid.
I want my fixed item to maintain the property of the grid. I think that when I add the fixed property, my item is taken out of the flow so it looses the grid property (applied to the main container). How can I maintain the property of the containing element to a contained element while assigning it a <code>position: fixed;</code> property ?

**Comment by madeinside** [comment]
I've found a simple solution, but I'm not sure if it's a good one.
I simply added the classe "container" to my menu container.
Is it right ?

**Comment by gld1982ltd** [comment]
Can you put up an example [pen](codepen.io)?

**Comment by madeinside** [comment]
It was almost 9 month ago.
I'm sorry but I've forget about the project,
doesn't even know if I've found a way to solve this issuer or not...
