### ISSUE TITLE
navbar/menu issue

### ISSUE THREAD

**Issue by JerryZhouSyd** [dhg/Skeleton#280]
this is a great project and I like it. 

it seems the navbar/menu in the index.html page has some issues and it disappeared when on small screen(mobile) and the navbar/menu on the large screen does not show second level list items when mouse hover.

**Comment by akhyarrh** [comment]
Doesn't related, because that docked navbar not included in skeleton. CMIIW

**Comment by JerryZhouSyd** [comment]
thanks for your reply
