### ISSUE TITLE
Missing http in the Font link

### ISSUE THREAD

**Issue by LeoJavaAI** [dhg/Skeleton#286]
I got version 2.0.4 from the website and found this

```
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
```

It needs to chang to 

```
  <link href="http://fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
```

**Comment by champsupertramp** [comment]
it sets the dynamic protocol and it's fine. what issues did you encounter with the latter?

**Comment by LeoJavaAI** [comment]
```
 GET file://fonts.googleapis.com/css?family=Raleway:400,300,600 net::ERR_FILE_NOT_FOUND
```

**Comment by finchalyzer** [comment]
Leaving out the protocol the site will use the same protocol that your website is using (http or https).
If you open the file locally, it uses the file protocol (so the file is not found at file://...).
I think it's perfectly fine to leave out the protocol. If you want to open the html file locally, add the http (or https) protocol manually.

**Comment by LeoJavaAI** [comment]
@kodsunpikselis The file in question is not a local file, so I do not agree

**Comment by champsupertramp** [comment]
@kodsunpikselis  is correct. In your log, you've opened the file locally.

**Comment by mgohin** [comment]
You need to open your web page via server like apache to serv files in the correct way (by using an url like `http://localhost/your_website`). You must have opened your web page by double clicking on it so it opened it in your browser with protocal `file://` and not `http://`

**Comment by itsdarrylnorris** [comment]
Should we close this issue since have been solve already ?

**Comment by LeoJavaAI** [comment]
yup

**Comment by itsdarrylnorris** [comment]
@Leo-G, can close this issue ? I'm not a maintainer nor the person that start this issue so I can close it.
