### ISSUE TITLE
“Tab” suffix

### ISSUE THREAD

**Issue by pilt** [dhg/Skeleton#29]
Hello!

First, thanks for Skeleton. It looks real nice and promising.

From the documentation:

```
<ul class="tabs">
  <li><a class="active" href="#simple">Simple</a></li>
</ul>
<ul class="tabs-content">
  <li class="active" id="simpleTab">…</li>
</ul>
```

It breaks standard fragment links and seems like unnecessary cruft.

```
<ul class="tabs">
  <li><a class="active" href="#simple">Simple</a></li>
</ul>
<ul class="tabs-content">
  <li class="active" id="simple">…</li>
</ul>
```

Works fine.

**Comment by pinktrink** [comment]
+1, I can agree that the "Tab" suffix is unnecessary.

**Comment by dhg** [comment]
Removed it as of Skeleton 1.1 released just now :) Thanks for this contribution!
