### ISSUE TITLE
Minimum width 550px requirement

### ISSUE THREAD

**Issue by t3hmrman** [dhg/Skeleton#298]
Hey it looks like currently skeleton has a requirement (in the media query) for screens to be at least 550px... That's not always the case -- is this something that will ever be addressed?

Other similar small libraries (notably [PureCSS](http://purecss.io)) allow specification for some default styling... However, the way pure does it doesn't quite fit in with the way skeleton is designed (as far as the semantic column class names)...

**Comment by benhinchley** [comment]
that 550px is just for the grid

**Comment by t3hmrman** [comment]
Yeah, that the feature I was trying to use... The following HTML wasn't working as I'd expected:

``` html
<div class="row">
  <div class="six columns">...</div>
  <div class="six columns">...</div>
</div>
```

The `columns` class was being applied properly (as it's minimum is 400px), but `six` was not. It's easy to see from skeleton.css why that is.

Is this intended of skeleton? That is to say, has Skeleton been written such that the smallest viewport it will support is 550px or above? Totally fine if that's the case of course, I just didn't read the docs well enough

**Comment by skunkface** [comment]
The grid is only supposed to show up when the viewport is larger than 550px. Smaller viewports default to a single column. `.column` will always work but `.six` will not have any effect until the viewport is larger than 550px.

**Comment by ghost** [comment]
In my Version called Skeleton plus I added mobile grids. But it was the first release and I working on it to make it better
http://github.com/oltmannsdaniel/skeleton-plus

**Comment by t3hmrman** [comment]
Oh I actually went back to using Pure... I made this ticket just to let people working on skeleton know of this use case.

**Comment by t3hmrman** [comment]
Closing this -- Pretty sure this doesn't need to be fixed/is something everyone's fine with
