### ISSUE TITLE
Add media query polyfill

### ISSUE THREAD

**Issue by necolas** [dhg/Skeleton#3]
Include some form of JS polyfill for browsers without support for media queries. Respond.js is one option.

**Comment by dhg** [comment]
Hey Necolas, 

So I seriously considered doing this with the initial release, but I decided to take the approach of graceful degradation with the first release. For now, I am going to stand by the decision, but I will make sure to listen if others have the same suggestion. I will also add a note in the docs about non CSS3 browsers and the link to respond.js. 

Thanks again for the contributions and helping make Skeleton better. You rock!

Cheers
