### ISSUE TITLE
Feature: 'Active' button

### ISSUE THREAD

**Issue by bradrobertson** [dhg/Skeleton#30]
Love the button styling!  

Would be interested in a button that has more oomph to it as well (like, say a blue, or darker grey button) that matches that styling.

**Comment by dhg** [comment]
Thanks so much for the contribution, but for now I am going to close this issue. I am adding this to my personal list of potential future ideas, but as Skeleton stands right now it is an entirely colorless palette. This is both to preserve the Spartan aesthetic, but also to emphasize that it is a "Skeleton" (not a stylistic package). 

Thanks again for your support and know your idea is definitely in my personal list for future thought!

Cheers
Dave
