### ISSUE TITLE
class name not compatible with emmet

### ISSUE THREAD

**Issue by TimeBandit** [dhg/Skeleton#300]
The Sublime Text plugin called Emmet allows you to write html in short form and then to expand it into full form using the Tab key. For example:

```
div.col-md-12
```

becomes

```
<div class="col-md-12">after pressing the Tab key for completion</div>
```

This is not possible with Skeleton as spaces between class words are not supported, meaning the whole thing must be typed out manually.

This is more of a feature request that a bug

**Comment by stevebobdob** [comment]
in Emmet, `div.twelve.columns` will expand to `<div class="twelve columns"></div>`

**Comment by TimeBandit** [comment]
Agreed, I was coming at this from the point of view of someone who is used to the bootstrap column definitions and is used to typing them in. In the future there may be competing skeleton packages, it might make adoption of this package easier if it seemed like a mini version of bootstrap or some other popular framework rather that introducing a new set of class names into the mix with people who are already accustomed to bootstrap/foundation/semantic-ui class naming conventions?
