### ISSUE TITLE
Project Dead

### ISSUE THREAD

**Issue by joexn** [dhg/Skeleton#313]
It seems that obviously this project has been abandoned. 

There is a new up to date version here: [Legacy Framework](http://legacyframework.xyz)

**Comment by ghost** [comment]
I already create a few days ago a plus Version of Skeleton. And it is not dead. http://github.com/oltmannsdaniel/skeleton-plus

**Comment by fanshuai** [comment]
What a pity :(

**Comment by awinecki** [comment]
@joexn, @oltmannsdaniel: what are the goals of Legacy Framework and skeleton-plus? Is there any particular reason to abandon this project?

The project's goal seems to be minimal, modern-looking, responsive framework. I think there's still going to be a need for such one. So, why not try to revive this project?

**Comment by joexn** [comment]
With modern web standards getting more advanced and some of the new features in HTML5, Skeleton is getting left behind. This is why I created Legacy, to keep the original Skeleton but adding more advanced features.

**Comment by awinecki** [comment]
That sounds interesting. I can't find GitHub page for Legacy Framework, though. Do you plan open sourcing the code here on GitHub?

It'd be awesome if you explained a bit more what industry / environment changes led you to update the project. More specifically, what kind of _advanced features_ have you added and what do you intend on adding.

Things I'd like to see in Skeleton:
- Easy install w/ `npm`
- Play nicely w/ webpack
- Less / Sass support
- Ditch Raleway font or make it _opt-in_ or changeable

**Comment by colus001** [comment]
+1 npm, webpack, preprocessir all I want.

**Comment by joexn** [comment]
I am quite new to Github so I'll look into it. I have been ill latley so I haven't been able to update the project as much as I'd like to. Hopefully soon I'll have everything sorted and I'll update you all on here

**Comment by joexn** [comment]
[Legacy Framework](https://github.com/joexn/Legacy-Framework) is now on GitHub!

**Comment by gld1982ltd** [comment]
Sorry. Late response. Skeleton is not dead!!! It has just moved to a community operated repo. [Skeleton Framework](https://github.com/skeleton-framework/skeleton-framework)

Installs with npm or bower, uses postcss, and is accepting pull requests!

**Comment by awinecki** [comment]
@gld1982ltd nice! I'll have a look later on.

Would be nice to add links to [Skeleton Framework](https://github.com/skeleton-framework/skeleton-framework) and [Legacy Framework](https://github.com/joexn/Legacy-Framework) to the `Readme.md` file.

Any chance, @dhg ?

**Comment by EminezArtus** [comment]
I loved this project for so long but now with flex-box it's almost obsolete.
Check this out its the basically the same concept but with flex-box http://milligram.io/
