### ISSUE TITLE
Legacy Framework

### ISSUE THREAD

**Issue by joexn** [dhg/Skeleton#319]
When I was learning how to code websites, I used Skeleton a lot. Unfortunately the creator doesn't really update this anymore, so I decided to code my own framework, Legacy. It is based of Skeleton, somewhat. Please rate it! It is a work in progress but I want it to grow!

[Legacy Framework](https://github.com/joexn/Legacy-Framework)

**Comment by fromthemills** [comment]
Looks nice!

**Comment by joexn** [comment]
Thank you for the feedback

**Comment by seb2411** [comment]
Nice I was looking for a replacement for Skeleton, as the project seem dead. I will try yours.

**Comment by samayo** [comment]
This is nice. I will be trying it today in my project. Keep up the good work.

**Comment by joexn** [comment]
@samayo, please keep me updated, I'd love to see what you've created.

**Comment by xcatliu** [comment]
Looks nice!
Another choice if you want to build a mobile website
http://getmobicss.com

**Comment by mathieujobin** [comment]
little late to the party... I am more of a backend guy and I just learn about skeleton, looks like it was exactly what I wanted... to my surprise, the last releases dates of 2014 ;(

**Comment by sinkaszab** [comment]
Seems dead, but remember, this is a boilerplate! (For me it still seems to be valid.)

**Comment by naveenlb** [comment]
Yes, dhg is working in Twitter Bootstrap team now.
