### ISSUE TITLE
There is a gap on the right when shrink down window size < 300px.

### ISSUE THREAD

**Issue by cyfyifanchen** [dhg/Skeleton#328]
any idea what's going on? 

![image](https://cloud.githubusercontent.com/assets/2340896/16626690/456e4c18-4367-11e6-8761-0e2278c9030a.png)

**Comment by NiklasBr** [comment]
This is a bug in Chrome's responsive debug mode, you will notice this works fine in browsers (including Chrome) if you set the window width to 223px (as your example).

**Comment by cyfyifanchen** [comment]
Thanks for your answer, but other sites aren't doing this in Chrome's responsive debug mode.

**Comment by cyfyifanchen** [comment]
![image](https://cloud.githubusercontent.com/assets/2340896/16825169/99011860-492f-11e6-8866-8fcc4a32d486.png)

This is screenshot of Amazon in Chrome developer tool. It doesn't seem to have the same problem.

**Comment by NiklasBr** [comment]
You should probably report this as a [Chrome issue](https://bugs.chromium.org/p/chromium/issues/list?q=component:Platform%3EDevTools) because it only happens when the Dev Tools are open, not when a regular window is <300px wide.

**Comment by cyfyifanchen** [comment]
Right, I thought that it be a Chrome issue at first, then I pulled up amazon.com to check. Apparently, it only happens here: http://getskeleton.com/

**Comment by NiklasBr** [comment]
It only happens in Chrome Dev Tools not when Dev Tools are disabled, therefore the easiest explanation is that it is an issue with the Dev Tools. If you resize a non-Dev Tools window to 300 px or less you can see that http://getskeleton.com/ works perfectly fine.

**Comment by cyfyifanchen** [comment]
Cool, thanks.
