### ISSUE TITLE
outdated jQuery version

### ISSUE THREAD

**Issue by rsaccon** [dhg/Skeleton#33]
is there a specific reason you are using jQuery 1.5.1 ? The latest stable version is 1.6.2

**Comment by pinktrink** [comment]
There's an open pull request that will port the tab system to good old fashioned JavaScript instead of jQuery.  This will eliminate the need for jQuery in the future.

**Comment by dhg** [comment]
Fixed :) Just referencing the latest jQuery version straight from the Google CDN and don't even include a local version. It was a compromise, but one that made the download lighter and simpler to use!
