### ISSUE TITLE
Buttons change appearance depending on background color

### ISSUE THREAD

**Issue by ghost** [dhg/Skeleton#37]
I really like Skeleton and it may sound trite, but the styling of the buttons really influenced me to take it serious (it just looks professional). However, I noticed that when I have a button on a dark background, it looks atrocious. I think this is because the button's gradient background is a transparent overlay rather than solid colors so it lets the background of the containing div bleed through.

I'm currently overriding base.css so that it displays consistently irrespective of the div behind the button - it'd be great if in future releases, I didn't have to override that aspect of the css.  Here's what I'm using (generated w/ http://www.colorzilla.com/gradient-editor/):

a.button,
button,
input[type="submit"],
input[type="reset"],
input[type="button"] {
    background: #f3f4f3; /\* Old browsers _/
    background: -moz-linear-gradient(top, #f3f4f3 0%, #c3c3c3 100%); /_ FF3.6+ _/
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#f3f4f3), color-stop(100%,#c3c3c3)); /_ Chrome,Safari4+ _/
    background: -webkit-linear-gradient(top, #f3f4f3 0%,#c3c3c3 100%); /_ Chrome10+,Safari5.1+ _/
    background: -o-linear-gradient(top, #f3f4f3 0%,#c3c3c3 100%); /_ Opera11.10+ _/
    background: -ms-linear-gradient(top, #f3f4f3 0%,#c3c3c3 100%); /_ IE10+ _/
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f3f4f3', endColorstr='#c3c3c3',GradientType=0 ); /_ IE6-9 _/
    background: linear-gradient(top, #f3f4f3 0%,#c3c3c3 100%); /_ W3C */
}

a.button:hover,
button:hover,
input[type="submit"]:hover,
input[type="reset"]:hover,
input[type="button"]:hover {
    background: #f4f5f4; /\* Old browsers _/
    background: -moz-linear-gradient(top, #f4f5f4 0%, #ababab 100%); /_ FF3.6+ _/
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#f4f5f4), color-stop(100%,#ababab)); /_ Chrome,Safari4+ _/
    background: -webkit-linear-gradient(top, #f4f5f4 0%,#ababab 100%); /_ Chrome10+,Safari5.1+ _/
    background: -o-linear-gradient(top, #f4f5f4 0%,#ababab 100%); /_ Opera11.10+ _/
    background: -ms-linear-gradient(top, #f4f5f4 0%,#ababab 100%); /_ IE10+ _/
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f4f5f4', endColorstr='#ababab',GradientType=0 ); /_ IE6-9 _/
    background: linear-gradient(top, #f4f5f4 0%,#ababab 100%); /_ W3C */
}

a.button:active,
button:active,
input[type="submit"]:active,
input[type="reset"]:active,
input[type="button"]:active {
    background: #f5f6f5; /\* Old browsers _/
    background: -moz-linear-gradient(top, #f5f6f5 0%, #989998 100%); /_ FF3.6+ _/
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#f5f6f5), color-stop(100%,#989998)); /_ Chrome,Safari4+ _/
    background: -webkit-linear-gradient(top, #f5f6f5 0%,#989998 100%); /_ Chrome10+,Safari5.1+ _/
    background: -o-linear-gradient(top, #f5f6f5 0%,#989998 100%); /_ Opera11.10+ _/
    background: -ms-linear-gradient(top, #f5f6f5 0%,#989998 100%); /_ IE10+ _/
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f5f6f5', endColorstr='#989998',GradientType=0 ); /_ IE6-9 _/
    background: linear-gradient(top, #f5f6f5 0%,#989998 100%); /_ W3C */
}

**Comment by dhg** [comment]
This is a great point! I will add a background color to the button so that they are more flexible on varying backgrounds for the next release!

**Comment by dhg** [comment]
Changed and fixed :) Not completely tested, but works like a boss in Chrome, FF (still need to test IE). Will do in next round of major testing.
