### ISSUE TITLE
 Error 'Bug', The input is not aligned vertically, it can not be in the center, middle

### ISSUE THREAD

**Issue by ghost** [dhg/Skeleton#383]
-

**Comment by pedroguilhermelima** [comment]
Ok, this can be closed. To solve add margin-left: calc (50% - 24%); /* remove 52% */ to class 'six columns'  in line 'media queries' for skeleton.css

Replace 

`  .six.columns                    { width: 48%; }
`

To
`  .six.columns { width: 48%; margin-left: calc(50% - 24%); } /* remover 52% from style in form and add here */
`

Regards,
Pedro Guilherme.

**Comment by pedroguilhermelima** [comment]
Hi, how are you?

**Description**
I had a problem and I solved it. I hope it's added.

**Summary**
1.  Change .six.columns { width: 48%;  } to .six.columns { width: 48%; margin-left: calc(50% - 24%); } 
Note:  If you want center, middle, vertical-align:middle. 

2- Or change .six.columns { width: 48%;  } to .six.columns { width: 48%; /* width: 100%; */ } 
Note:  If you want center, middle, vertical-align:middle. 

 **Answer in :** 
https://stackoverflow.com/questions/55544528/how-to-center-align-vertically-to-center-and-middle-with-skeleton-css-boilerpla
