### ISSUE TITLE
gh-pages branch?

### ISSUE THREAD

**Issue by njt1982** [dhg/Skeleton#39]
Could you make a GH Pages branch? This would allow the CSS files to be added using GitHub as a "CDN" for quickly wireframing sites, eg:
http://skeleton.github.com/

**Comment by beaumartinez** [comment]
Well, it'd be [dhgamache.github.com/Skeleton](http://dhgamache.github.com/Skeleton).

You could always fork the repo yourself and set up GitHub Pages for that, and then pull request it back in, it shouldn't take more than a few minutes as all you'd have to do is add the CSS to the `gh-pages` branch.

**Comment by dhg** [comment]
Great suggestions, but in an effort to keep Skeleton simple I'm just going to keep with the remote docs on www.getskeleton.com and the source here on Github.
