### ISSUE TITLE
add support for 240 width?

### ISSUE THREAD

**Issue by zanona** [dhg/Skeleton#40]
Hi, I've just found this nice tool for testing responsive design:
http://mattkersley.com/responsive/

And could notice he uses 240 for small phones....I'm not sure how often it is used but do you think it might be interesting to add it to skeleton.css?

Cheers

**Comment by dhg** [comment]
There are definitely some phones that could benefit from a 240 width, but I designed Skeleton with some of the more common dimensions in mind. I also have chosen to keep the grid no larger than 960 for similar reasons. Great suggestion, but for now I think the media queries that exist are a good balance of control and number of potential viewport sizes.
