### ISSUE TITLE
Nevermind for this issue, you can delete

### ISSUE THREAD

**Issue by AdrianATP** [dhg/Skeleton#409]

**Comment by heyeddi** [comment]
So, wrong place to file that? I don't see the description anymore about the DOCTORES site.
But seems the search thing is not something skeleton provides.

**Comment by AdrianATP** [comment]
> So, wrong place to file that? I don't see the description anymore about the DOCTORES site.
> But seems the search thing is not something skeleton provides.

I accidentally created in the wrong place. Sorry for the inconvenience.

**Comment by uaktags** [comment]
Can't you close your own issue?

**Comment by AdrianATP** [comment]
@uaktags I was trying to delete it, but  I closed it.
