### ISSUE TITLE
no margins for combination of .alpha & .omega for width of 768px

### ISSUE THREAD

**Issue by felixhirschfeld** [dhg/Skeleton#43]
First of all... Skeleton kicks ass! 

I've added:

alpha.omega { margin-left: 0; margin-right: 0; } to the @media only screen and (min-width: 768px) and (max-width: 959px) {}

because i didn't like that .omega overrides the margins of .alpha

Maybe i fixed a very tiny bug? Tell me :)

**Comment by dhg** [comment]
Great catch. Sorry it's taken basically forever for me to go through the issues here. Fixed and pushed live.
