### ISSUE TITLE
Package with a JavaScript polyfill

### ISSUE THREAD

**Issue by Olical** [dhg/Skeleton#46]
I saw in [the support section](http://www.getskeleton.com/#support) of the website that you will not try to implement a JavaScript fallback. I think just bundling with either of these already proven implementations would be a good idea.
- [Respond](https://github.com/scottjehl/Respond) - My personal favorite and what seems to be the most polished.
- [css3-mediaqueries-js](http://code.google.com/p/css3-mediaqueries-js/) - A promising alternative.

I don't know if you have a reason not to, but I think it would be good to provide a useful script for a fallback if the user requires it. It saves them hunting around for a polyfill and potentially using one that does not work correctly.

**Comment by kamranayub** [comment]
That's one of the first things I did; simply adding in respond.js made the grid work fine in IE7 (which we unfortunately have to target).

**Comment by dhg** [comment]
I'm sticking to my guns on this one fellas, but I have linked up respond.js in the Skeleton docs. I really appreciate you pushing me to at least suggest a polyfill so people aren't confused or lost as to what a good solution for older browsers.
