### ISSUE TITLE
Merge pull requests?

### ISSUE THREAD

**Issue by vshvedov** [dhg/Skeleton#61]
Hi,

as author of https://github.com/helios-technologies/skeleton-rails Rails gem, i'm very interested: do you plan to future development and improvement of Skeleton CSS?
Looks like you have 10 pull requests, and few of them looks very good.

Thanks.

**Comment by dhg** [comment]
Yo, 

Good call. I haven't really been doing any active development on Skeleton, but I owe it to the community to get in here and see what makes sense to pull in. Working through the pull requests and issues tonight :)

**Comment by vshvedov** [comment]
(y)
