### ISSUE TITLE
Improve branching model

### ISSUE THREAD

**Issue by gnugat** [dhg/Skeleton#63]
Hi, Iwould like to suggest an improvement in the branching model.
The best would be to follow these advices: http://nvie.com/posts/a-successful-git-branching-model/

But basically, what would be great is to create an unstable "develop" branch, while keeping the master branch as the stable one.
This would allow, by creating a version tag each time a merge is done to master, to make change logs easier to follow.

I hope it makes sense :) .

**Comment by dhg** [comment]
@gnugat Great suggestion sir. Honestly, Skeleton is not under heavy development, but I will start creating more stable releases at shorter intervals.

I will be closing this issue, but will take the suggestion to heart. 

Cheers.
