### ISSUE TITLE
.alpha.omega not congruent with the rest of Skeleton

### ISSUE THREAD

**Issue by adamjohnson** [dhg/Skeleton#68]
I'm referencing issue #43

While this certainly does fix the issue for tablet, wouldn't a better fix be to simply remove the margin-xyz: 10px from `alpha` and `omega` for the tablet media query? 

In other words, now its:

```
.column.alpha, .columns.alpha     { margin-left: 0; margin-right: 10px; }
.column.omega, .columns.omega     { margin-right: 0; margin-left: 10px; }
.alpha.omega     { margin-left: 0; margin-right: 0; }
```

Wouldn't this be better and more congruent with the rest of Skeleton? 

```
.column.alpha, .columns.alpha     { margin-left: 0; }
.column.omega, .columns.omega     { margin-right: 0; }
```

**Comment by dhg** [comment]
Alpha and omega no longer used in V2.0 – simply always nest within a `.row` and avoids this issue.
