### ISSUE TITLE
Micro-Clearfix?

### ISSUE THREAD

**Issue by dhg** [dhg/Skeleton#7]
Need to test the micro-clearfix across browsers. If it works, it will be a more lightweight solution that I would love to use!  (http://nicolasgallagher.com/micro-clearfix-hack/)

Originally suggested by Necolas (https://github.com/necolas)

**Comment by Calvein** [comment]
It works well, it's used on [HTML5 Boilerplate](https://github.com/paulirish/html5-boilerplate) too (Necolas is a part of H5BP).

**Comment by dhg** [comment]
Awesome. That sounds like a winner then. I already have it in my local code and just need to quickly test it before I push live. Will probably be out in the next day :)

Cheers!

**Comment by dhg** [comment]
Hey - 

Are there are advantages to using this updated clearfix method? I'm looking at my existing one and the "updated" version and it seems like the primary difference is just a `display: table` instead of block (which means I can remove explicity `width: 0; height: 0;`).

It's possible I am missing a huge advantage to the switch, but for now the different in length is three lines of CSS...does the render actually change or get any advantage?

Thanks again for your contribution!

Cheers!

**Comment by dhg** [comment]
Continued to play with the micro clearfix and found no real advantage (besides 2 lines of removed CSS). Will continue to use the existing clearfix method unless somebody has an awesome reason to change (in which case I would love to chat about it). 

Cheers
