### ISSUE TITLE
getskeleton site shows 12 columns - confusing

### ISSUE THREAD

**Issue by mraaroncruz** [dhg/Skeleton#72]
Hi,
I was just introduced to skeleton through Spree.  I really like it.
I was very confused that on the site you give a 12 column example though there are 16 columns in your grid.
The only mention to 16 columns is if you view the source for the example and there is this

```
<!-- Give column value in word form (one, two..., twelve) -->
<div class="sixteen columns">
    <h1>Full Width Column</h1>
</div>
```

which seems super vague to me and almost misleading.
I looked at the source to see that indeed there are 16 columns.  I don't know if a less experienced dev would do the same.
I will be using this project often.  Thanks for the time you put into it!
aaron

**Comment by ibrent** [comment]
agreed.  this threw me too.

**Comment by shovanco** [comment]
Same. Where can I find 12 grid?

**Comment by edhedges** [comment]
If you look that is just an example of how it works. View the source of that page and you can see the side bar takes up 3 columns and the actual content of the site takes up 12 columns but it has the class of offset-by-one. this makes up the total of 16 total columns.

Skeleton is a 16 column css framework. It is very flexible so if you want a 12 column grid you can modify the css or you can make offset-by-two on each side of your website thus having a 12 column grid. I think this will be very skinny and 16 gives designers/developers for flexibility and power anyways.

This issue should probably be closed as it really isn't an issue but more of a css question.

**Comment by mraaroncruz** [comment]
Hi @edhedges,
Please read/re-read my original post.  I don't see how this could be seen as a question.
Thanks.

**Comment by edhedges** [comment]
@pferdefleisch Ah ok. I am sorry. I guess my response is a little more relevant to @ibrent and @shovansargunam. I do agree for beginners it could be confusing. A good way around this would be to explain that the grid is 16 columns but here is an example using 12 columns?

**Comment by mraaroncruz** [comment]
np :)
Yeah, I think that a mention in the opening paragraphs would be super helpful.

> Skeleton has a familiar, lightweight 960 grid as its base

could be

> Skeleton has a familiar, lightweight 960px, **16 column** grid as its base

for example.

**Comment by shovanco** [comment]
Thanks guys for your help. I am still getting my head around. I have a theme build on Skeleton and I have designed in Foundation Framework (foundation.zurb.com), Trying to hack into Skeleton and make it work for my design. 

Appreciate your comments.

**Comment by javiercr** [comment]
The same happened to me. The documentation is a bit confusing in this aspect.

**Comment by karthur26** [comment]
+1

**Comment by bfintal** [comment]
+1

**Comment by mraaroncruz** [comment]
As an example of how Twitter Bootstrap takes care of this same exact issue
http://twitter.github.com/bootstrap/scaffolding.html#gridSystem
It is in bold in the description text that there are 12 columns.

**Comment by 0CT0F035** [comment]
+1

**Comment by keithslater** [comment]
This also had me confused. Maybe just updating the documentation would solve this issue?

**Comment by zarino** [comment]
+1

**Comment by joahg** [comment]
move to close - new getskeleton site doesn't have error

**Comment by dhg** [comment]
This was mad confusing and something that should have been taken care of (or at least explained). New site doesn't suffer from same confusing issue, so that's good! Closing in light of v2.0
