### ISSUE TITLE
IE8 Support?

### ISSUE THREAD

**Issue by contempoinc** [dhg/Skeleton#74]
Anyone else seeing major issues in IE8?

Skeleton Demo (included in download) in IE8
http://contempographicdesign.com/wp-content/uploads/2012/03/skeleton-demo-ie8.png

My Theme IE8
http://contempographicdesign.com/wp-content/uploads/2012/03/re3-ie8.png

Same site in Chrome:
http://contempographicdesign.com/wp-content/uploads/2012/03/re3-chrome.png

It works great in IE9+, Chrome, Firefox, Safari but fails miserably in IE8 below. I've tried both the HTML5 Shiv and IE9.js

**Comment by dhg** [comment]
IE8 and older don't support media queries. I noted it shortly in the docs, but if you want to get it looking good on IE7 and below you'll have to include a media-query JS polyfill like https://github.com/scottjehl/Respond. Not a bug, I just choose to allow for graceful degradation on older browsers.

Hope that helps and please re-open if this doesn't solve your issue.

**Comment by contempoinc** [comment]
That did the trick, thank ya sir!
