### ISSUE TITLE
Content jumps when a scrollbar appears

### ISSUE THREAD

**Issue by bijoutrouvaille** [dhg/Skeleton#75]
Hi, I'm building a site that, using ajax and web sockets, loads content when links are clicked without refreshing the page itself. Some pages are small and fit into the screen without the need of a scrollbar to the right, and some are long so they get one. 

So when the scrollbar appears or disappears the entire page contents jump to the left or to the right by the width of the bar. You can watch this happen on getskeleton.com by deleting divs starting with "what is it" going down, until the scrollbar hides itself.

I wish I could offer a solution to this almost insignificant glitch, but I'm not a designer and don't know the new css all that well.

In any case thank you for a great framework.

**Comment by bijoutrouvaille** [comment]
Here's a line of script that, pasted in your developer console on getskeleton.com, will demonstrate what I mean:

$('header').siblings().remove()

**Comment by dhg** [comment]
So this is an issue that's true of any site. If the content is shorter than the viewport, a scrollbar is not necessary. A good fix for this though, should you want to avoid shifting, is to force a scrollbar no matter what. To do so, just add:

 `body { overflow-y: scroll }` 

That should make it happen! I'm going to close this, but please re-open and let me know if this doesn't solve your issue.
