### ISSUE TITLE
File type form input not rendered as other form inputs are

### ISSUE THREAD

**Issue by LeMogwai** [dhg/Skeleton#76]
Hello,

I'm attempting to build my web application with this excellent (!) skeleton, but I miss something I can not do by myself.

The form inputs are all nice and look alike, but _the file type input stays 'raw' with the default look_.

Could you please enhance the CSS to make it look like the other form inputs and buttons ?

Thank you

LeMogwaï.

**Comment by danielboendergaard** [comment]
The file input element can't be styled with css like other input elements, that's why it looks "raw".
You'd have to use a some javascript to be able to make them look like the others.

**Comment by EvilChookie** [comment]
You can use some creative CSS to style a file input - although it can be kinda rough:

http://www.quirksmode.org/dom/inputfile.html#link2

**Comment by LeMogwai** [comment]
Well, thanks four your suggestions.
I'll have a look at them and give you feedback.

**Comment by dhg** [comment]
Styling file inputs isn't something that's really achievable in a way that's effective across all browsers without a significant amount of hacks and trickery. V2 continues to leave these issue untouched and isn't something I plan on addressing unless there's significant support for it in the future.
