### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by margagn** [dhg/Skeleton#77]
I am trying to add a "sticky footer" to my web site based on skeleton but I can't get it to work correctly. I am doing this based on the instruction on this website: http://www.cssstickyfooter.com/using-sticky-footer-code.html. In Chrome I get an extra pixel or two in the height of the page which result in a vertical scrollbar and in IE the main container becomes left-aligned.

Any idea how I should implement this properly based on Skeleton? Thank you Dave for the great work!

**Comment by ghost** [comment]
Yeah... I tried that too and had the same annoying result in Chrome. I ended up just putting the footer at the bottom (below all the content). It's one of those "hacks" that sometimes don't work as written on the tin.

**Comment by sdrib** [comment]
I don't have this problem. Is this still an issue?

**Comment by chrisjohnleah** [comment]
Yes, please help me address this issue, maybe a little code snippet / blog post example of how to successfully insert a sticky footer into the bare bones download template of Skeleton.

**Comment by jordanmkoncz** [comment]
Yeah I'd love to know how to do this as well.

**Comment by chrisjohnleah** [comment]
I managed to get it working following this guys. http://signalkraft.com/sticky-footer-in-960-grid-system

**Comment by jordanmkoncz** [comment]
Cheers for that, working perfectly for me.

**Comment by chrisjohnleah** [comment]
No worries, it's what the communities about I guess.

**Comment by sdrib** [comment]
Yeah I used a similar system

**Comment by dhg** [comment]
Seems like everyone fixed things here! I can't imagine Skeleton having anything specific that would interfere with sticky footers of any kind. Let me know if anyone struggles with this again!

**Comment by mahmoud** [comment]
This is still enough of a problem that I think including this updated solution specific to skeleton may help others in the future: https://github.com/mahmoud/skeleton_sticky_footer
