### ISSUE TITLE
Two Small Form Issues

### ISSUE THREAD

**Issue by mnooner256** [dhg/Skeleton#9]
I really like what you have done here. But I ran into a couple of minor issues when dealing with forms.

First, you have no styles defined for input elements of the button, submit, or reset type. I just added the appropriate [] selectors to the base.css file.

```
a.button, 
button,
input[type="submit"],
input[type="reset"],
input[type="button"] {
    etc.
}
```

Along the same lines, you do not have a style setup for legend tags. The legend tag is supposed to be used whenever you use a fieldset. I noticed on your site you opted for a label instead. I just added legend to the label's definition and it was all fixed.

**Comment by dhg** [comment]
Hi There, 

Both of these suggestions were great. Both went into the CSS and were pushed to an updated release (V1.0.2). 

Thanks for the contribution!
