### ISSUE TITLE
Superscript and Subscript need re-styling after reset

### ISSUE THREAD

**Issue by mlawren** [dhg/Skeleton#97]
`sub` and `sup` are at present no different from any other text inside a `p` tag. For `sup` at least I suggest something like the following:

```
sup { font-size: 80%; vertical-align: top; }
```

**Comment by jamiebuilds** [comment]
See: https://github.com/dhgamache/Skeleton/issues/102#issuecomment-8840223

**Comment by dhg** [comment]
Resolved with the release of V2.0 and the inclusion of normalize.css :)

**Comment by mlawren** [comment]
> Resolved with the release of V2.0 and the inclusion of normalize.css :)

Thanks Dave, great to see some movement on Skeleton!

**Comment by dhg** [comment]
Thanks @mlawren!
