### ISSUE TITLE
How can i make a one fourth column row?

### ISSUE THREAD

**Issue by Linh35** [dhg/Skeleton#98]
I want to make a row with 4 columns and i want it to behave just like a one-third column but with 4 elements

**Comment by rakelley** [comment]
skeleton is a 16 column grid, 1/4 of 16 is 4, so just use: 

```
<div class="row">
    <div class="four columns"></div>
    <div class="four columns"></div>
    <div class="four columns"></div>
    <div class="four columns"></div>
</div>
```

the one-third/two-thirds classes only exist because 1/3 of 16 isn't an integer.

**Comment by jamiebuilds** [comment]
Should be closed

**Comment by joahg** [comment]
move to close

**Comment by dhg** [comment]
Now would be a `<div class="three columns">` since the transition to twelve columns.

**Comment by thadeubrito** [comment]
But, if a have a loop to show a list of posts, and each post is a box. how can I do it?

```
<div class="row">
    <%= for post in @posts do %>
        <div class="four columns"><%=post.title%></div>
</div>
```

**Comment by benhinchley** [comment]
currently since you can only have 12columns per row, you would have to create a new row every three posts according to your markup

**Comment by thadeubrito** [comment]
omg, it is not good. But I will do it manually. Thanks @benhinchley
